# practicepython.org
# Övning 18
#
"""
Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that 
the user guessed correctly in the correct place, they have a “cow”. For every digit the user 
guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them 
how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. 
Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
"""
from random import randint

def help():
    print("Välkommen till gissningsspelet!")
    print("Jag har slumpat ett tal med 4 siffror, du ska gissa")
    print("vilket tal jag tänkt på!")
    print("R: Rätt tal på rätt på plats")
    print("S: Rätt tal, men inte på rätt plats")
    print("-: Talet skall inte vara med alls")
    print("----- Skriv exit för att avsluta spelet -----")

def compare(hemligt, gissning):
    res = []
   
    for i in range(0, len(hemligt)):
        if hemligt[i] == gissning[i]:
            res.append("R")
        else:
            if gissning[i] in hemligt:
                res.append("S")
            else:
                res.append("-")
    return "".join(res)

def main():
    hemligt = str(randint(10000, 99999))[1:5]
    #print("Hemligt: " + hemligt)
    playing = True
    antalGissningar = 0
    help()
    
    while playing:
        antalGissningar+=1
        gissning = input("Ange din gissning: ")
        if gissning == "exit":
            quit()
        resultat = compare(hemligt, gissning)
        print("Resultat:         ", resultat)
        if resultat == "RRRR":
            print("Yeah!")
            playing = False
    print("Du klarade det efter {} försök!".format(antalGissningar))
    
if __name__ == "__main__": main()